### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by ShadenSmith** [bvdberg/ctest#10]
ctest is not distributed with any licensing information. I'm hesitant to use it on my own projects without that info. Is it possible to distribute it under a permissive license? I'm a fan of MIT :-).

**Comment by ShadenSmith** [comment]
Apologies, I missed the Apache licensing in the source code. Perhaps a file with that info would also be a good idea for those browsing the project.

**Comment by bvdberg** [comment]
Hi,

Certainly a good idea! I'll add it when i get proper internet access again..
Thx,
Bas
