### ISSUE TITLE
Runtime memory error with magic pointer

### ISSUE THREAD

**Issue by ChisholmKyle** [bvdberg/ctest#26]
I ran some tests compiled with gcc memory sanitizer options `-fsanitize=address -fsanitize=leak -fsanitize=undefined` and the output was fine except for the following error at the beginning of the output:

    ctest.h:500:14: runtime error: load of address 0x000106c07ef8 with insufficient space for an object of type 'unsigned int'
    0x000106c07ef8: note: pointer points here
     00 00 00 00  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  88 67 29 59 ff 7f 00 00  98 67 29 59

This corresponds to the line 500 in ctest.h:
    
    if (t->magic != __CTEST_MAGIC) break;

I've never used the "deadbeef" `#define __CTEST_MAGIC (0xdeadbeef)` magic pointer technique so I'm not sure what's going on here. Anyone know if this is a real issue or if it can be easily fixed?

**Comment by bvdberg** [comment]
Haha! The magic that happens inside ctest is indeed impossible to understand for sanitizers...
The way we lookup tests *without* having a linker file is to add a known 'internal' test in the same
section as all the other tests. From that known pointer, we search forwards and backwards for other
tests by checking the MAGIC. I was surprised that the MAGIC was still 0xdeadbeef, it might be better to change this to some other value perhaps...

**Comment by ChisholmKyle** [comment]
Thanks for the explanation! 0xdeadbeef is a fun pointer, why change what works, right?
