### ISSUE TITLE
Make a release of the library

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [bvdberg/ctest#40]
Hi!

Can you make a release, please? It'll help a lot with packaging your library into different dependency managers (like Conan).

Thank you!

**Comment by bvdberg** [comment]
I have create a tag. Since this is a source only lib, that's the only thing I can think of. Or did you have anything else in mind?

**Comment by ZaMaZaN4iK** [comment]
No, that's enough. Thank you a lot!

I think it can be closed now.
