### ISSUE TITLE
Does CTest support setup and teardown functions per suite of tests (instead of per test)?

### ISSUE THREAD

**Issue by supersonicnumbers** [bvdberg/ctest#47]
Hi, 

Neat library! 

As the tittle suggests, I was wondering if it's possible to have a setup/teardown function per each suite of tests instead of per each tests inside a suite?

Thanks!

**Comment by bvdberg** [comment]
Hi ,

Thx!

Do you mean you want a special setup and teardown function that's called
once per suite?

That is not supported at the moment..
The setup can be easily added in the normal setup in combination with a
global Boolean...

The teardown is nastier..

What use case do you have?

Bas

**Comment by supersonicnumbers** [comment]
Hi,

> Do you mean you want a special setup and teardown function that's called
once per suite?

Yes, I meant this.

My use case is ordinary testing (systems programming). I am currently looking for a test library and did found a couple of interesting ones (criterion, unity,...) but much prefer yours due to its small footprint, however the possibility of having a setup/teardown per suite would be quite important, as it makes it easier (and faster) to run large test files.

Have a nice day.

**Comment by bvdberg** [comment]
Hi,

i would not be hard to add i think, so maybe you could attempt that. The
macro code is quite dense however,

Best regards,
Bas

**Comment by supersonicnumbers** [comment]
Thanks.

Is this something you would consider to eventually add yourself to the library (or accept a PR) ?

Curious to hear your thoughts.

**Comment by bvdberg** [comment]
Hoi Supersonic,

i have no other requests of people needing something like that, so i think
it's best if you modify it yourself.

Good luck,
Bas

**Comment by supersonicnumbers** [comment]
Thanks for the info!
