### ISSUE TITLE
Compile using `-std=c99` and function `kill` not found

### ISSUE THREAD

**Issue by htv2012** [bvdberg/ctest#58]
I just learned about CTest so I wanted to give it a test drive. However, when I compile (using either `gcc` or `clang`) with the `-std=C99`, I got an error saying that function `kill` is used before declared.

# Steps

1. Copy `main.c` and `ctest.h` from this repository into a directory
2. Create `test1.c` with the following content

        #include "ctest.h"
        
        CTEST(suite, test1) {
            ASSERT_STR("foo", "foo");
        }
        
3. Compile with one of these commands:

        gcc -o mytest *.c                  # no error
        gcc -o mytest -std=c99 *.c  # error, see below

Error:
```
% gcc -std=c99 -o gcctest *.c                                                                                                           [master]
In file included from main.c:25:
ctest.h: In function ‘sighandler’:
ctest.h:505:5: error: implicit declaration of function ‘kill’ [-Wimplicit-function-declaration]
  505 |     kill(getpid(), signum);
      |     ^~~~
```

# More Info

I got similar result with `clang`:

```
% clang -std=c99 -o mytest *.c                                                                                                          [master]
In file included from main.c:25:
./ctest.h:505:5: error: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  505 |     kill(getpid(), signum);
      |     ^
1 error generated.
```

**Comment by htv2012** [comment]
When I comment out the following line in main, then the code will compile with `-std=c99` without error:

```c
#define CTEST_SEGFAULT
```

**Comment by bvdberg** [comment]
indeed. Kill() is a bit weird in that there is no proper include. I've fixed it now by just manually declaring it. Thx!
So just do a pull, that should fix your issue, even with CTEST_SEGFAULT enabled

**Comment by htv2012** [comment]
Thank you for the snappy fix. I did try up to `-std=c17`  without any problem.
